#ifndef TITAN_MODEL_SELECT_H__
#define TITAN_MODEL_SELECT_H__

#include <rtconfig.h>

#ifndef TITAN_USE_HANDWRITING_MODEL
#define TITAN_USE_HANDWRITING_MODEL 0
#endif

#define TITAN_USING_HANDWRITING_MODEL (TITAN_USE_HANDWRITING_MODEL)
#define TITAN_USING_FACE_MODEL        (!TITAN_USE_HANDWRITING_MODEL)

#endif
