import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()
CPPPATH = [cwd]

src += Glob('*.c')

if GetDepend('BSP_USING_USB_PAUD') or GetDepend('BSP_USING_USB_PAUD_FSP'):
    src = [f for f in src if os.path.basename(str(f)) != 'r_usb_pcdc_descriptor.c']

objs = DefineGroup('usb_pcdc', src, depend = ['BSP_USING_USB_PCDC'], CPPPATH = CPPPATH)

Return('objs')
